Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -35,4 +35,37 @@ jobs:
           run: dotnet restore apis/poi/poi.sln
       
         - name: Build
-          run: dotnet build --no-restore apis/poi/poi.sln    
+          run: dotnet build --no-restore apis/poi/poi.sln  
+          
+        - name: Test
+          run: dotnet test --no-build --verbosity normal -r testresults --logger "trx" apis/poi/poi.sln
+      
+        - name: API POI Tests Report
+          uses: dorny/test-reporter@v1
+          if: success() || failure()  # run this step even if previous step failed
+          with:
+            name: API POI Tests       # Name of the check run which will be created
+            path: apis/poi/tests/UnitTests/testresults/*.trx,apis/poi/tests/IntegrationTests/testresults/*.trx   #Path to test results
+
+  docker_build_and_push:
+      if: github.ref == 'refs/heads/master'
+      runs-on: ubuntu-latest
+      needs: build
+      
+      steps:
+      - uses: actions/checkout@v2
+
+#- name: Docker login
+      - shell: bash
+        name: Docker Login
+        env:
+          ACR_KEY: ${{ secrets.ACR_KEY }}
+          DOCKER_USER: ${{ secrets.DOCKER_USER }}
+          ACR: ${{ env.ACR_URL}}
+        run: docker login "$ACR" -u "$DOCKER_USER" -p "$ACR_KEY"
+
+      - shell: bash
+        name: Docker build
+        env:
+          ACR: ${{ env.ACR_URL}}
+        run: docker build -t "$ACR"/devopsoh/api-poi:${{github.run_number}} --build-arg build_version=${{github.run_number}} apis/poi/web
